spring:
  application:
    name: clips-stats-getter

fetch:
  broadcasters-ids: ${fetch.broadcaster-id}
---
spring:
  config:
    activate:
      on-cloud-platform: kubernetes
  main:
    banner-mode: off

logging:
  config: classpath:logback-kubernetes.xml
